In [1]:
from aeon.datasets import load_classification
X, y, meta_data = load_classification("ECG200")
print(" Shape of X = ", X.shape)
print(" Meta data = ", meta_data)

 Shape of X =  (200, 1, 96)
 Meta data =  {'problemname': 'ecg200', 'timestamps': False, 'missing': False, 'univariate': True, 'equallength': True, 'classlabel': True, 'targetlabel': False, 'class_values': ['-1', '1']}


In [2]:
X.shape

(200, 1, 96)

In [3]:
y.shape

(200,)

In [4]:
meta_data

{'problemname': 'ecg200',
 'timestamps': False,
 'missing': False,
 'univariate': True,
 'equallength': True,
 'classlabel': True,
 'targetlabel': False,
 'class_values': ['-1', '1']}

In [33]:
y = y.astype(int)
y

array([-1,  1, -1, -1,  1,  1, -1, -1,  1,  1,  1,  1,  1,  1, -1,  1,  1,
        1, -1, -1,  1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,
        1, -1,  1,  1,  1,  1,  1,  1,  1, -1, -1,  1, -1, -1,  1, -1,  1,
        1,  1, -1,  1,  1, -1, -1,  1,  1,  1, -1,  1,  1,  1, -1,  1,  1,
        1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
       -1, -1,  1, -1,  1, -1,  1,  1, -1,  1,  1, -1, -1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1, -1, -1,  1, -1, -1, -1,  1,  1,  1, -1,
        1, -1,  1,  1,  1,  1,  1, -1,  1, -1,  1,  1,  1, -1, -1,  1,  1,
        1,  1, -1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
       -1, -1, -1,  1, -1, -1, -1, -1,  1,  1, -1, -1, -1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1, -1, -1, -1,
       -1,  1,  1,  1, -1,  1,  1,  1,  1,  1, -1, -1,  1])

In [35]:
y[y == -1] = 0
y

array([0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1])

In [36]:
import pandas as pd
df = pd.DataFrame(data=X[:, 0, :])
df['label'] = y
df.head()

0         1         2         3         4         5         6  \
0  0.502055  0.542163  0.722383  1.428885  2.136516  2.281149  1.936274   
1  0.147647  0.804668  0.367771  0.243894  0.026614 -0.274402  0.096731   
2  0.316646  0.243199  0.370471  1.063738  1.678187  1.759558  1.697717   
3  1.168874  2.075901  1.760141  1.606446  1.949046  1.302842  0.459332   
4  0.648658  0.752026  2.636231  3.455716  2.118157  0.520620 -0.188627   

          7         8         9  ...        87        88        89        90  \
0  1.468890  1.008845  0.380282  ...  0.610298  0.638894  0.684679  0.583238   
1 -0.747731 -1.609777 -1.179593  ... -0.400228  0.176084  1.111768  2.438428   
2  1.612159  1.168188  0.499957  ...  0.610621  0.552900  0.566786  0.604002   
3  0.516412  0.852180  0.989227  ...  0.723888  1.323947  2.136488  1.746597   
4  0.780818  0.933775  0.701402  ... -0.136787 -0.340237 -0.089441 -0.080297   

         91        92        93        94        95  label  
0  0.640522  0.708585  0.705011  0.713815  0.433765      0  
1  2.734889  1.736054  0.036857 -1.265074 -0.208024      1  
2  0.777068  0.812345  0.748848  0.818042  0.539347      0  
3  1.470220  1.893512  1.256949  0.800407  0.731540      0  
4 -0.192584 -0.304704 -0.454556  0.314590  0.582190      1  

[5 rows x 97 columns]

In [37]:
df.to_csv('ECG200_raw.csv', index=False)

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.5, random_state=0)

In [39]:
X_train.shape

(100, 1, 96)

In [40]:
from sktime.transformations.panel.rocket import Rocket
from sktime.datasets import load_unit_test
import multiprocessing

trf = Rocket(num_kernels=20, n_jobs=multiprocessing.cpu_count()-1) 
trf.fit(X_train) 
X_train_transform = trf.transform(X_train) 
X_test_transform = trf.transform(X_test) 

In [41]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(random_state=0).fit(X_train_transform, y_train)
clf.score(X_test_transform, y_test)

/home/samir/miniconda3/envs/gendis_pp/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.86

In [43]:
truth_class_one = y_test.astype(int)
# truth_class_one[truth_class_one != 1] = 0
truth_class_one[0:10]

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [44]:
y_pred = clf.predict(X_test_transform)
y_pred[0:10]

array([0, 1, 1, 1, 1, 0, 1, 1, 0, 0])

In [45]:
y_pred_proba = clf.predict_proba(X_test_transform)
y_pred_proba[0:10]

array([[0.90360245, 0.09639755],
       [0.02973659, 0.97026341],
       [0.01389127, 0.98610873],
       [0.00777547, 0.99222453],
       [0.14870608, 0.85129392],
       [0.81918018, 0.18081982],
       [0.07711489, 0.92288511],
       [0.03101249, 0.96898751],
       [0.87638892, 0.12361108],
       [0.64659942, 0.35340058]])

In [46]:
proba_class_one = y_pred_proba[:, 1]
proba_class_one[0:10]

array([0.09639755, 0.97026341, 0.98610873, 0.99222453, 0.85129392,
       0.18081982, 0.92288511, 0.96898751, 0.12361108, 0.35340058])

In [47]:
import numpy as np
model_error = np.absolute(truth_class_one - proba_class_one)
model_error[0:10]

array([0.09639755, 0.02973659, 0.01389127, 0.00777547, 0.14870608,
       0.81918018, 0.07711489, 0.03101249, 0.87638892, 0.35340058])

In [48]:
df_err = pd.DataFrame(data=X_test[:, 0, :])
df_err['truth'] = y_test
df_err['clf_pred'] = y_pred
df_err['clf_prob'] = proba_class_one
df_err['error'] = model_error
df_err.head()

0         1         2         3         4         5         6  \
0  1.088076  1.564040  1.368890  1.250157  1.491498  1.682589  1.226951   
1  0.955804  1.603964  2.728597  4.147563  2.942624  1.382093  0.037531   
2  1.709221  2.752852  1.682990  1.241862 -0.037972 -0.217589  0.789646   
3  0.179500  1.038409  1.946421  2.705141  1.670706 -0.101167 -1.578876   
4  0.465348  0.860500  1.247617  1.987052  2.265494  1.639544  0.933286   

          7         8         9  ...        90        91        92        93  \
0  0.343969 -0.335317 -0.729320  ...  2.150796  2.385066  1.993872  1.760286   
1 -0.339903  0.465481  0.797179  ... -0.137032 -0.510956 -0.414687 -0.289843   
2  0.547428  0.302104  0.339065  ...  0.111021  0.308668  0.048724  0.072167   
3 -0.750906  0.175310  0.064901  ...  0.567132  0.136757  0.444768  0.151050   
4  0.252858 -0.256997 -0.006043  ...  0.325771  0.032964  0.081087  0.201554   

         94        95  truth  clf_pred  clf_prob     error  
0  1.269218  0.399103      0         0  0.096398  0.096398  
1 -0.471944 -0.345898      1         1  0.970263  0.029737  
2  0.348025  0.658488      1         1  0.986109  0.013891  
3  0.193378  0.451709      1         1  0.992225  0.007775  
4  0.316433  0.347387      1         1  0.851294  0.148706  

[5 rows x 100 columns]

In [49]:
df_err.to_csv('ECG200_processed_error.csv', index=False)